In [59]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [58]:
red = pd.read_csv('/content/drive/MyDrive/Colab Notebooks/wine+quality/winequality-red.csv' , delimiter=';')

In [60]:
white = pd.read_csv('/content/winequality-white.csv' , delimiter=';')

In [61]:
red.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1599 entries, 0 to 1598
Data columns (total 12 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   fixed acidity         1599 non-null   float64
 1   volatile acidity      1599 non-null   float64
 2   citric acid           1599 non-null   float64
 3   residual sugar        1599 non-null   float64
 4   chlorides             1599 non-null   float64
 5   free sulfur dioxide   1599 non-null   float64
 6   total sulfur dioxide  1599 non-null   float64
 7   density               1599 non-null   float64
 8   pH                    1599 non-null   float64
 9   sulphates             1599 non-null   float64
 10  alcohol               1599 non-null   float64
 11  quality               1599 non-null   int64
dtypes: float64(11), int64(1)
memory usage: 150.0 KB

In [62]:
column_means = red.mean(numeric_only=True)
print("Mean of each column:")
print(column_means)

TypeError: 'Series' object is not callable